server:
  port: 8081
logging:
  config: classpath: logback.xml

xxl:
  job:
    accessToken:
    admin:
      address: http://127.0.0.1:8080/xxl-job-admin
  executor:
    ip: 127.0.0.1
    port: 9999
    appname: xxl-job-executor-sample
    logpath: /data/applogs/xxl-job/jobhandler
    logretentiondays: -1
