server:
  port: 9999
spring:
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/xxl-job?useSSL=false&useUnicode=true&characterEncoding=utf-8
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j2
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  thymeleaf:
    cache: false

  freemarker:
    cache: false
    settings:
      template_update_delay: 0
      default_encoding: UTF-8
      output_encoding: UTF-8
      locale: zh_CN
      number_format: 0.##########
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:s
      classic_compatible: true
      template_exception_handler: ignore
xxljobmall:
  host: smtp.163.com
  port: 25
  username: ovono802302@163.com
  password: asdfzxcv
  sendFrom: ovono802302@163.com
  sendNick: \u300a\u4efb\u52a1\u8c03\u5ea6\u5e73\u53f0XXL-JOB\u300b
xxl:
  job:
    accessToken:
    login:
      username: admin
      password: 123456
